name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ./ --upgrade
      - name: Test with pytest
        run: |
          pip install pytest
<<<<<<< HEAD
          python3 -m pytest
=======
          python3 -m pytest
>>>>>>> 4fc3371e1d904d5a0bddb54f116b32e5a7858416
