name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - name: Prepare Selenium
       # https://github.com/marketplace/actions/setup-chromedriver
        uses: nanasess/setup-chromedriver@master
      - name: Launch browser
      - name: Start XVFB
        run: |
         - google-chrome --version
         - export DISPLAY=:99
         - chromedriver --url-base=/wd/hub &
            sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional, disables headless mode
      - name: Install 
        run: |
          python -m pip install --upgrade pip
          pip install chromedriver-autoinstaller
          pip install -r requirements.txt
          pip install pytest

      - name: Test with pytest
        run: |
          python -m pytest
